alter table public.orders
add column if not exists payment_received numeric(10, 2),
add column if not exists payment_method text,
add column if not exists received_by text,
add column if not exists paid_at timestamptz;

alter table public.orders
drop constraint if exists orders_payment_method_check;

alter table public.orders
add constraint orders_payment_method_check
check (payment_method is null or payment_method in ('CASH', 'ONLINE', 'SPLIT'));

alter table public.orders
drop constraint if exists orders_received_by_check;

alter table public.orders
add constraint orders_received_by_check
check (received_by is null or received_by in ('NEETA', 'TRUPTI', 'MULTIPLE'));

create table if not exists public.order_payment_entries (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  amount numeric(10, 2) not null check (amount > 0),
  method text not null check (method in ('CASH', 'ONLINE')),
  received_by text not null check (received_by in ('NEETA', 'TRUPTI')),
  notes text,
  updated_by text not null check (updated_by in ('NEETA', 'TRUPTI')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists order_payment_entries_order_id_idx
on public.order_payment_entries(order_id, created_at desc);

create table if not exists public.payment_audit_log (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  action_type text not null,
  actor text not null check (actor in ('NEETA', 'TRUPTI')),
  summary text not null,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists payment_audit_log_order_id_idx
on public.payment_audit_log(order_id, created_at desc);
